//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// xscgen -n SSP_API.Types.Xsd C:\shemas\bki_api_sch\qcb_result.xsd
namespace SSP_API.Types.Xsd
{
    

    /// <summary>
    /// <para>Результат регистрации запроса</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Результат регистрации запроса")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Результат", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Результат", Namespace="")]
    public partial class RequestResult
    {
        /// <summary>
        /// <para>Идентификатор, присвоенный ответу</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор, присвоенный ответу")]
        [System.Xml.Serialization.XmlElementAttribute("ИдентификаторОтвета")]
        public ResultIdAnswer ResultId { get; set; }
        
        /// <summary>
        /// <para>Запрос обработан успешно (в случаях когда не требуется ответ)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Запрос обработан успешно (в случаях когда не требуется ответ)")]
        [System.Xml.Serialization.XmlElementAttribute("Успешно")]
        public ResultSuccess Success { get; set; }
        
        /// <summary>
        /// <para>Описание ошибки</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание ошибки")]
        [System.Xml.Serialization.XmlElementAttribute("Ошибка")]
        public ResultError Error { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "1.2";
        
        /// <summary>
        /// <para>Версия схемы</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Версия схемы")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Версия")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>ОГРН КБКИ сформировавшего квитанцию</para>
        /// <para>Основной государственный регистрационный номер юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{13}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН КБКИ сформировавшего квитанцию")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{13}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ОГРН")]
        public string Ogrn { get; set; }
    }

    /// <summary>
    /// <para>Идентификатор, присвоенный ответу</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("РезультатИдентификаторОтвета", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResultIdAnswer
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Идентификатор запроса, в ответ на который подготовлена данная квитанция</para>
        /// <para>Уникальный идентификатор</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор запроса, в ответ на который подготовлена данная квитанция")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдентификаторЗапроса")]
        public string RequestId { get; set; }
        
        /// <summary>
        /// <para>Прогнозируемое время готовности ответа в миллисекундах</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Прогнозируемое время готовности ответа в миллисекундах")]
        [System.Xml.Serialization.XmlAttributeAttribute("ВремяГотовности")]
        public long ReadyTime { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ВремяГотовности property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadyTimeSpecified { get; set; }
    }

    /// <summary>
    /// <para>Запрос обработан успешно (в случаях когда не требуется ответ)</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("РезультатУспешно", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResultSuccess
    {
        
        /// <summary>
        /// <para>Идентификатор запроса, в ответ на который подготовлена данная квитанция</para>
        /// <para>Уникальный идентификатор</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор запроса, в ответ на который подготовлена данная квитанция")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдентификаторЗапроса")]
        public string RequestId { get; set; }
    }

    /// <summary>
    /// <para>Описание ошибки</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("РезультатОшибка", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResultError
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Код ошибки</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код ошибки")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Код")]
        public string Code { get; set; }
    }
}
