//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// xscgen -n |C:\shemas\bki_api_sch\qcb_request.xsd=SSP_API.Types.Xsd -n |C:\shemas\bki_api_sch\qcb_common.xsd=SSP_API.Types.Xsd C:\shemas\bki_api_sch\qcb_request.xsd C:\shemas\bki_api_sch\qcb_common.xsd
using SSP_API.Types.Enums;

namespace SSP_API.Types.Xsd
{


    /// <summary>
    /// <para>Коды сроков действия согласия</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Коды сроков действия согласия")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("КодыСрокаСогласия", Namespace="")]
    public enum ConsentExpirationType
    {
        
        /// <summary>
        /// <para>Согласие действительно в течение шести месяцев со дня его оформления</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Согласие действительно в течение шести месяцев со дня его оформления")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>Согласие действительно в течение года со дня его оформления</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Согласие действительно в течение года со дня его оформления")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <summary>
        /// <para>В течение срока действия согласия с субъектом кредитной истории были заключены договор займа (кредита), договор лизинга, договор залога, договор поручительства, выдана независимая гарантия</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("В течение срока действия согласия с субъектом кредитной истории были заключены до" +
            "говор займа (кредита), договор лизинга, договор залога, договор поручительства, " +
            "выдана независимая гарантия")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <summary>
    /// <para>Коды целей выдачи согласия</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Коды целей выдачи согласия")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("КодыЦелиСогласия", Namespace="")]
    public enum PurposeIssuingConsentType
    {
        
        /// <summary>
        /// <para>Потребительский заем (кредит) на приобретение автомобиля</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) на приобретение автомобиля")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>Потребительский микрозаем</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Потребительский микрозаем")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <summary>
        /// <para>Потребительский заем (кредит) нецелевой</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) нецелевой")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <summary>
        /// <para>Потребительский заем (кредит) с расходным лимитом (кредитная линия, овердрафт)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) с расходным лимитом (кредитная линия, овердрафт)")]
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <summary>
        /// <para>Иной потребительский заем (кредит)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной потребительский заем (кредит)")]
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <summary>
        /// <para>Поручительство гражданина-потребителя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Поручительство гражданина-потребителя")]
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <summary>
        /// <para>Ипотека, предоставленная гражданином-потребителем</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ипотека, предоставленная гражданином-потребителем")]
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <summary>
        /// <para>Иной залог, предоставленный гражданином-потребителем</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной залог, предоставленный гражданином-потребителем")]
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <summary>
        /// <para>Иной потребительский договор</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной потребительский договор")]
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <summary>
        /// <para>Заем (кредит) на развитие бизнеса</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на развитие бизнеса")]
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <summary>
        /// <para>Заем (кредит) на пополнение оборотных средств</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на пополнение оборотных средств")]
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <summary>
        /// <para>Заем (кредит) на покупку оборудования</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на покупку оборудования")]
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <summary>
        /// <para>Заем (кредит) на строительство</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на строительство")]
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <summary>
        /// <para>Заем (кредит) на приобретение ценных бумаг</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на приобретение ценных бумаг")]
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <summary>
        /// <para>Иной заем (кредит)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной заем (кредит)")]
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <summary>
        /// <para>Лизинг</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Лизинг")]
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <summary>
        /// <para>Независимая гарантия</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Независимая гарантия")]
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <summary>
        /// <para>Поручительство</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Поручительство")]
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <summary>
        /// <para>Страхование</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Страхование")]
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        /// <summary>
        /// <para>Ипотека</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ипотека")]
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <summary>
        /// <para>Иной залог</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной залог")]
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <summary>
        /// <para>Иной договор</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной договор")]
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <summary>
        /// <para>Кредитный мониторинг в рамках действующего договора</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Кредитный мониторинг в рамках действующего договора")]
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <summary>
        /// <para>Прием на работу</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Прием на работу")]
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <summary>
        /// <para>Маркетинговые исследования</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Маркетинговые исследования")]
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        /// <summary>
        /// <para>Научные исследования</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Научные исследования")]
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        
        /// <summary>
        /// <para>Контроль данных</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Контроль данных")]
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        
        /// <summary>
        /// <para>Иное</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иное")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <summary>
    /// <para>Коды оснований передачи согласия правопреемнику</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Коды оснований передачи согласия правопреемнику")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("КодыОснованийПередачиСогласия", Namespace="")]
    public enum GroundTransferringConsentAssigneeType
    {
        
        /// <summary>
        /// <para>Согласие субъекта кредитной истории передано правопреемнику по заключенному договору займа (кредита) или иному договору, информация об обязательствах по которым передается в бюро кредитных историй</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Согласие субъекта кредитной истории передано правопреемнику по заключенному догов" +
            "ору займа (кредита) или иному договору, информация об обязательствах по которым " +
            "передается в бюро кредитных историй")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>Согласие субъекта кредитной истории передано кредитной организации, осуществляющей обслуживание денежных требований по договору займа (кредита), уступленных специализированному финансовому обществу или ипотечному агенту</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Согласие субъекта кредитной истории передано кредитной организации, осуществляюще" +
            "й обслуживание денежных требований по договору займа (кредита), уступленных спец" +
            "иализированному финансовому обществу или ипотечному агенту")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <summary>
    /// <para>Коды видов пользователей кредитной истории</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Коды видов пользователей кредитной истории")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("КодыВидаПользователя", Namespace="")]
    public enum CreditHistoryUserType
    {
        
        /// <summary>
        /// <para>Индивидуальный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Индивидуальный предприниматель")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>Кредитная организация</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Кредитная организация")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <summary>
        /// <para>Микрофинансовая организация</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Микрофинансовая организация")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <summary>
        /// <para>Кредитный потребительский кооператив</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Кредитный потребительский кооператив")]
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <summary>
        /// <para>Сельскохозяйственный кредитный потребительский кооператив</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сельскохозяйственный кредитный потребительский кооператив")]
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <summary>
        /// <para>Ломбард</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ломбард")]
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <summary>
        /// <para>Лизинговая компания</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Лизинговая компания")]
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <summary>
        /// <para>Субъект страхового дела</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Субъект страхового дела")]
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <summary>
        /// <para>Коллекторская организация</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Коллекторская организация")]
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <summary>
        /// <para>Иной пользователь</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной пользователь")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <summary>
    /// <para>Сведения о согласии на получение кредитного отчета субъекта</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Сведения о согласии на получение кредитного отчета субъекта")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипСогласие", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsentInfo
    {
        
        /// <summary>
        /// <para>Информация о лице, которому выдано согласие</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация о лице, которому выдано согласие")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Выдано")]
        public ConsentGranted Granted { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PurposeConsentInfo> _purpose;
        
        /// <summary>
        /// <para>Цель выдачи согласия субъекта</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Цель выдачи согласия субъекта")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Цель")]
        public System.Collections.ObjectModel.Collection<PurposeConsentInfo> Purpose
        {
            get
            {
                return _purpose;
            }
            private set
            {
                _purpose = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConsentInfo" /> class.</para>
        /// </summary>
        public ConsentInfo()
        {
            this._purpose = new System.Collections.ObjectModel.Collection<PurposeConsentInfo>();
        }
        
        /// <summary>
        /// <para>Информация о договоре, сведения об обязательствах по которому подлежат передаче в БКИ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация о договоре, сведения об обязательствах по которому подлежат передаче в БКИ")]
        [System.Xml.Serialization.XmlElementAttribute("Договор")]
        public ConsentAgreement Contract { get; set; }
        
        /// <summary>
        /// <para>Хэш-код для согласия субъекта кредитной истории</para>
        /// <para xml:lang="en">Pattern: [\da-f]{64}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Хэш-код для согласия субъекта кредитной истории")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\da-f]{64}")]
        [System.Xml.Serialization.XmlElementAttribute("ХэшКод")]
        public string Hash { get; set; }
        
        /// <summary>
        /// <para>Дата получения согласия от субъекта</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата получения согласия от субъекта")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаВыдачи", DataType="date")]
        public System.DateTime DateIssue { get; set; }
        
        /// <summary>
        /// <para>Код срока действия согласия субъекта</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код срока действия согласия субъекта")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("СрокДействия")]
        public ConsentExpirationType ConsentExpiration { get; set; }
        
        /// <summary>
        /// <para>Основание передачи согласия правопреемнику</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание передачи согласия правопреемнику")]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснованиеПередачи")]
        public GroundTransferringConsentAssigneeType BasisTransfer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ОснованиеПередачи property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BasisTransferSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _warnedAboutResponsibility = "1";
        
        /// <summary>
        /// <para>Об ответственности за совершение административных правонарушений, установленной статьями 5.53 и 14.29 Кодекса Российской Федерации об административных правонарушениях предупрежден</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Об ответственности за совершение административных правонарушений, установленной статьями 5.53 и 14.29 Кодекса Российской Федерации об административных правонарушениях предупрежден")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ОбОтветственностиПредупрежден")]
        public string WarnedAboutResponsibility
        {
            get
            {
                return _warnedAboutResponsibility;
            }
            set
            {
                _warnedAboutResponsibility = value;
            }
        }
    }

    /// <summary>
    /// <para>Информация о лице, которому выдано согласие</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипСогласиеВыдано", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsentGranted
    {
        
        /// <summary>
        /// <para>Информация о юридическом лице, которому выдано согласие</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация о юридическом лице, которому выдано согласие")]
        [System.Xml.Serialization.XmlElementAttribute("ЮридическоеЛицо")]
        public LegalEntityInfo LegalEntity { get; set; }
        
        /// <summary>
        /// <para>Информация об индивидуальном предпринимателе, которому выдано согласие</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация об индивидуальном предпринимателе, которому выдано согласие")]
        [System.Xml.Serialization.XmlElementAttribute("ИндивидуальныйПредприниматель")]
        public IndividualEntrepreneurInfo IndividualEntrepreneur { get; set; }
        
        /// <summary>
        /// <para>Информация об иностранном юридическом лице, которому выдано согласие</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация об иностранном юридическом лице, которому выдано согласие")]
        [System.Xml.Serialization.XmlElementAttribute("ИностранноеЮЛ")]
        public ForeignLegalEntityInfo ForeignLegalEntity { get; set; }
        
        /// <summary>
        /// <para>Информация об иностранном предпринимателе, которому выдано согласие</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация об иностранном предпринимателе, которому выдано согласие")]
        [System.Xml.Serialization.XmlElementAttribute("ИностранныйПредприниматель")]
        public ForeignIndividualEntrepreneurInfo ForeignEntrepreneur { get; set; }
    }
    
    /// <summary>
    /// <para>Юридическое лицо</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Юридическое лицо")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипЮЛБазовый", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegalEntityInfo
    {
        
        /// <summary>
        /// <para>ИНН юридического лица</para>
        /// <para>Индивидуальный номер налогоплательщика юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{10}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{10}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИНН")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН юридического лица</para>
        /// <para>Основной государственный регистрационный номер юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{13}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{13}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРН")]
        public string Ogrn { get; set; }
        
        /// <summary>
        /// <para>Полное наименование юридического лица</para>
        /// <para>Наименование юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([А-ЯЁ0-9:;,/"\.\(\)\\!-])+([ ][А-ЯЁ0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Полное наименование юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ПолноеНаименование")]
        public string Fullname { get; set; }
    }
    
    /// <summary>
    /// <para>Индивидуальный предприниматель</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Индивидуальный предприниматель")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИПБазовый", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IndividualEntrepreneurInfo
    {
        
        /// <summary>
        /// <para>ИНН индивидуального предпринимателя</para>
        /// <para>Индивидуальный номер налогоплательщика физического лица</para>
        /// <para xml:lang="en">Pattern: \d{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИННИП")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН индивидуального предпринимателя</para>
        /// <para>Основной государственный регистрационный номер индивидуального предпринимателя</para>
        /// <para xml:lang="en">Pattern: \d{15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРНИП")]
        public string Ogrn { get; set; }
        
        /// <summary>
        /// <para>ФИО индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ФИО индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public SSP_API.Types.Xsd.FullName Fullname { get; set; }
    }
    
    /// <summary>
    /// <para>Иностранное юридическое лицо</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Иностранное юридическое лицо")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИЮБазовый", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignLegalEntityInfo
    {
        
        /// <summary>
        /// <para>Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</para>
        /// <para>Номер налогоплательщика присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер налогоплательщика, присвоенный уполномоченным органом иностранного государс" +
            "тва, или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомерНП")]
        public string Number { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер в стране регистрации (инкорпорации) или его аналог</para>
        /// <para>Регистрационный номер присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер в стране регистрации (инкорпорации) или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("РегНомер")]
        public string RegNumber { get; set; }
        
        /// <summary>
        /// <para>Полное наименование иностранного юридического лица</para>
        /// <para>Наименование иностранного юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([A-Z0-9:;,/"\.\(\)\\!-])+([ ][A-Z0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Полное наименование иностранного юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([A-Z0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][A-Z0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ПолноеНаименование")]
        public string Fullname { get; set; }
    }
    
    /// <summary>
    /// <para>Иностранный предприниматель</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Иностранный предприниматель")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИностранныйПредпринимательБазовый", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignIndividualEntrepreneurInfo
    {
        
        /// <summary>
        /// <para>Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</para>
        /// <para>Номер налогоплательщика присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомерНП")]
        public string Number { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер в стране регистрации (инкорпорации) или его аналог</para>
        /// <para>Регистрационный номер присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер в стране регистрации (инкорпорации) или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("РегНомер")]
        public string RegNumber { get; set; }
        
        /// <summary>
        /// <para>ФИО иностранного предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ФИО иностранного предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public SSP_API.Types.Xsd.FullName Fullname { get; set; }
    }
    
    /// <summary>
    /// <para>Цель запроса/выдачи согласия</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Цель запроса/выдачи согласия")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипЦель", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurposeConsentInfo
    {
        
        /// <summary>
        /// <para>Код цели</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код цели")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КодЦели")]
        public TargetCodeType TargetCode { get; set; }
        
        /// <summary>
        /// <para>Описание иной цели</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание иной цели")]
        [System.Xml.Serialization.XmlAttributeAttribute("Описание")]
        public string Description { get; set; }
    }

    /// <summary>
    /// <para>Код цели</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипЦельКодЦели", Namespace="", AnonymousType=true)]
    public enum TargetCodeType
    {

        /// <summary>
        /// <para>Потребительский заем (кредит) на приобретение автомобиля</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Потребительский заем (кредит) на приобретение автомобиля")]
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) на приобретение автомобиля")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <summary>
        /// <para>Потребительский микрозаем</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Потребительский микрозаем")]
        [System.ComponentModel.DescriptionAttribute("Потребительский микрозаем")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <summary>
        /// <para>Потребительский заем (кредит) нецелевой</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Потребительский заем (кредит) нецелевой\"")]
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) нецелевой")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <summary>
        /// <para>Потребительский заем (кредит) с расходным лимитом (кредитная линия, овердрафт)</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Потребительский заем (кредит) с расходным лимитом (кредитная линия, овердрафт)")]
        [System.ComponentModel.DescriptionAttribute("Потребительский заем (кредит) с расходным лимитом (кредитная линия, овердрафт)")]
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <summary>
        /// <para>Иной потребительский заем (кредит)</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной потребительский заем (кредит)")]
        [System.ComponentModel.DescriptionAttribute("Иной потребительский заем (кредит)")]
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <summary>
        /// <para>Поручительство гражданина-потребителя</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Поручительство гражданина-потребителям")]
        [System.ComponentModel.DescriptionAttribute("Поручительство гражданина-потребителя")]
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <summary>
        /// <para>Ипотека, предоставленная гражданином-потребителем</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Ипотека, предоставленная гражданином-потребителем")]
        [System.ComponentModel.DescriptionAttribute("Ипотека, предоставленная гражданином-потребителем")]
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <summary>
        /// <para>Иной залог, предоставленный гражданином-потребителем</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной залог, предоставленный гражданином-потребителем")]
        [System.ComponentModel.DescriptionAttribute("Иной залог, предоставленный гражданином-потребителем")]
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <summary>
        /// <para>Иной потребительский договор</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной потребительский договор")]
        [System.ComponentModel.DescriptionAttribute("Иной потребительский договор")]
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,

        /// <summary>
        /// <para>Заем (кредит) на развитие бизнеса</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Заем (кредит) на развитие бизнеса")]
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на развитие бизнеса")]
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <summary>
        /// <para>Заем (кредит) на пополнение оборотных средств</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Заем (кредит) на пополнение оборотных средств")]
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на пополнение оборотных средств")]
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <summary>
        /// <para>Заем (кредит) на покупку оборудования</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Заем (кредит) на покупку оборудования")]
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на покупку оборудования")]
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <summary>
        /// <para>Заем (кредит) на строительство</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Заем (кредит) на строительство")]
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на строительство")]
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <summary>
        /// <para>Заем (кредит) на приобретение ценных бумаг</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Заем (кредит) на приобретение ценных бумаг")]
        [System.ComponentModel.DescriptionAttribute("Заем (кредит) на приобретение ценных бумаг")]
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <summary>
        /// <para>Иной заем (кредит)</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной заем (кредит)")]
        [System.ComponentModel.DescriptionAttribute("Иной заем (кредит)")]
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <summary>
        /// <para>Лизинг</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Лизинг")]
        [System.ComponentModel.DescriptionAttribute("Лизинг")]
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <summary>
        /// <para>Независимая гарантия</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Независимая гарантия")]
        [System.ComponentModel.DescriptionAttribute("Независимая гарантия")]
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <summary>
        /// <para>Поручительство</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Поручительство")]
        [System.ComponentModel.DescriptionAttribute("Поручительство")]
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <summary>
        /// <para>Страхование</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Страхование")]
        [System.ComponentModel.DescriptionAttribute("Страхование")]
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        /// <summary>
        /// <para>Ипотека</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Ипотека")]
        [System.ComponentModel.DescriptionAttribute("Ипотека")]
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <summary>
        /// <para>Иной залог</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной залог")]
        [System.ComponentModel.DescriptionAttribute("Иной залог")]
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <summary>
        /// <para>Иной договор</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иной договор")]
        [System.ComponentModel.DescriptionAttribute("Иной договор")]
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <summary>
        /// <para>Кредитный мониторинг в рамках действующего договора</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Кредитный мониторинг в рамках действующего договора")]
        [System.ComponentModel.DescriptionAttribute("Кредитный мониторинг в рамках действующего договора")]
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <summary>
        /// <para>Прием на работу</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Прием на работу")]
        [System.ComponentModel.DescriptionAttribute("Прием на работу")]
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <summary>
        /// <para>Маркетинговые исследования</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Маркетинговые исследования")]
        [System.ComponentModel.DescriptionAttribute("Маркетинговые исследования")]
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,

        /// <summary>
        /// <para>Научные исследования</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Научные исследования")]
        [System.ComponentModel.DescriptionAttribute("Научные исследования")]
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,

        /// <summary>
        /// <para>Контроль данных</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Контроль данных")]
        [System.ComponentModel.DescriptionAttribute("Контроль данных")]
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,

        /// <summary>
        /// <para>Иное</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Иное")]
        [System.ComponentModel.DescriptionAttribute("Иное")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипСогласиеДоговор", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsentAgreement
    {
        
        /// <summary>
        /// <para>Дата заключения договора</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата заключения договора")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Дата", DataType="date")]
        public System.DateTime Date { get; set; }
    }
    
    /// <summary>
    /// <para>Индивидуальный предприниматель</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Индивидуальный предприниматель")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИП", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IndividualEntrepreneur
    {
        private IndividualEntrepreneur() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="IndividualEntrepreneur"/>
        /// </summary>
        /// <param name="inn">ИНН</param>
        /// <param name="ogrn">ОГРН</param>
        /// <param name="snils">СНИЛС</param>
        /// <param name="fullName">ФИО</param>
        /// <param name="document">Документ удостоверяющий личность</param>
        /// <param name="dateBirth">Дата рождения</param>
        /// <param name="placeBirth">Место рождения</param>
        public IndividualEntrepreneur(
            string inn,
            string ogrn,
            string snils,
            FullName fullName,
            EntrepreneurIdentityDocument document,
            DateTime dateBirth,
            string placeBirth)
        {
            Inn = inn;
            Ogrn = ogrn;
            Snils = snils;
            Fullname = fullName;
            Document = document;
            DateBirth = dateBirth;
            PlaceBirth = placeBirth;
        }

        /// <summary>
        /// <para>ИНН индивидуального предпринимателя</para>
        /// <para>Индивидуальный номер налогоплательщика физического лица</para>
        /// <para xml:lang="en">Pattern: \d{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИННИП")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН индивидуального предпринимателя</para>
        /// <para>Основной государственный регистрационный номер индивидуального предпринимателя</para>
        /// <para xml:lang="en">Pattern: \d{15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРНИП")]
        public string Ogrn { get; set; }
        
        /// <summary>
        /// <para>СНИЛС индивидуального предпринимателя</para>
        /// <para>Страховой номер индивидуального лицевого счета</para>
        /// <para xml:lang="en">Pattern: \d\d\d-\d\d\d-\d\d\d \d\d.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("СНИЛС индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d\\d\\d-\\d\\d\\d-\\d\\d\\d \\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СНИЛС")]
        public string Snils { get; set; }
        
        /// <summary>
        /// <para>ФИО индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ФИО индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public SSP_API.Types.Xsd.FullName Fullname { get; set; }
        
        /// <summary>
        /// <para>Документ удостоверяющий личность индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Документ удостоверяющий личность индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ДокументЛичности")]
        public SSP_API.Types.Xsd.EntrepreneurIdentityDocument Document { get; set; }
        
        /// <summary>
        /// <para>Дата рождения индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата рождения индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождения", DataType="date")]
        public System.DateTime DateBirth { get; set; }
        
        /// <summary>
        /// <para>Место рождения индивидуального предпринимателя</para>
        /// <para>Место рождения</para>
        /// <para xml:lang="en">Pattern: ([А-ЯЁ]+([ -][А-ЯЁ]+)*)|([A-Z]+([ -][A-Z]+)*).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Место рождения индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([А-ЯЁ]+([ -][А-ЯЁ]+)*)|([A-Z]+([ -][A-Z]+)*)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("МестоРождения")]
        public string PlaceBirth { get; set; }
    }
    
    /// <summary>
    /// <para>Юридическое лицо</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Юридическое лицо")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипЮЛ", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegalEntitySource))]
    public partial class LegalEntity
    {

        /// <summary>
        /// <para>ИНН юридического лица</para>
        /// <para>Индивидуальный номер налогоплательщика юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{10}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{10}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИНН")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН юридического лица</para>
        /// <para>Основной государственный регистрационный номер юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{13}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{13}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРН")]
        public string Ogrn { get; set; }
        
        /// <summary>
        /// <para>Полное наименование юридического лица</para>
        /// <para>Наименование юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([А-ЯЁ0-9:;,/"\.\(\)\\!-])+([ ][А-ЯЁ0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Полное наименование юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ПолноеНаименование")]
        public string FullName { get; set; }
        
        /// <summary>
        /// <para>Сокращенное наименование юридического лица</para>
        /// <para>Наименование юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([А-ЯЁ0-9:;,/"\.\(\)\\!-])+([ ][А-ЯЁ0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сокращенное наименование юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][А-ЯЁ0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.Xml.Serialization.XmlElementAttribute("СокращенноеНаименование")]
        public string AbbreviatedName { get; set; }
        
        /// <summary>
        /// <para>Иное наименование юридического лица</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иное наименование юридического лица")]
        [System.Xml.Serialization.XmlElementAttribute("ИноеНаименование")]
        public object OtherName { get; set; }
        
        /// <summary>
        /// <para>Код вида пользователя кредитной истории</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код вида пользователя кредитной истории")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КодВидаПользователя")]
        public CreditHistoryUserType UserType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _signRegistrationRF = "1";
        
        /// <summary>
        /// <para>Признак регистрации в Российской Федерации</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Признак регистрации в Российской Федерации")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ПризнакРегистрацииРФ")]
        public string SignRegistrationRF
        {
            get
            {
                return _signRegistrationRF;
            }
            set
            {
                _signRegistrationRF = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Иностранное юридическое лицо</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Иностранное юридическое лицо")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИЮ", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeignLegalEntitySource))]
    public partial class ForeignLegalEntity
    {
        
        /// <summary>
        /// <para>Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</para>
        /// <para>Номер налогоплательщика присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер налогоплательщика, присвоенный уполномоченным органом иностранного государс" +
            "тва, или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомерНП")]
        public string TaxpayerNumber { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер в стране регистрации (инкорпорации) или его аналог</para>
        /// <para>Регистрационный номер присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер в стране регистрации (инкорпорации) или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("РегНомер")]
        public string RegNumber { get; set; }
        
        /// <summary>
        /// <para>Идентификатор LEI</para>
        /// <para>Идентификатор LEI</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{20}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор LEI")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z0-9]{20}")]
        [System.Xml.Serialization.XmlElementAttribute("LEI")]
        public string Lei { get; set; }
        
        /// <summary>
        /// <para>Полное наименование иностранного юридического лица</para>
        /// <para>Наименование иностранного юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([A-Z0-9:;,/"\.\(\)\\!-])+([ ][A-Z0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Полное наименование иностранного юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([A-Z0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][A-Z0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ПолноеНаименование")]
        public string FullName { get; set; }
        
        /// <summary>
        /// <para>Сокращенное наименование юридического лица</para>
        /// <para>Наименование иностранного юридического лица</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: ([A-Z0-9:;,/"\.\(\)\\!-])+([ ][A-Z0-9:;,/"\.\(\)\\!-]+)*.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сокращенное наименование юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([A-Z0-9:;,/\"\\.\\(\\)\\\\!-])+([ ][A-Z0-9:;,/\"\\.\\(\\)\\\\!-]+)*")]
        [System.Xml.Serialization.XmlElementAttribute("СокращенноеНаименование")]
        public string AbbreviatedName { get; set; }
        
        /// <summary>
        /// <para>Иное наименование иностранного юридического лица</para>
        /// <para>Наименование</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иное наименование иностранного юридического лица")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlElementAttribute("ИноеНаименование")]
        public string OtherName { get; set; }
        
        /// <summary>
        /// <para>Код вида пользователя кредитной истории</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код вида пользователя кредитной истории")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КодВидаПользователя")]
        public CreditHistoryUserType UserType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _signRegistrationRF = "0";
        
        /// <summary>
        /// <para>Признак регистрации в Российской Федерации</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Признак регистрации в Российской Федерации")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ПризнакРегистрацииРФ")]
        public string SignRegistrationRF
        {
            get
            {
                return _signRegistrationRF;
            }
            set
            {
                _signRegistrationRF = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Иностранный предприниматель</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Иностранный предприниматель")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ТипИностранныйПредприниматель", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignEntrepreneur
    {
        private ForeignEntrepreneur() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="ForeignEntrepreneur"/>
        /// </summary>
        /// <param name="taxpayerNumber">Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</param>
        /// <param name="regNumber">Регистрационный номер в стране регистрации (инкорпорации) или его аналог, присвоенный иностранной организации</param>
        /// <param name="fullName">ФИО</param>
        /// <param name="document">Документ, удостоверяющий личность</param>
        /// <param name="dateBirth">Дата рождения</param>
        /// <param name="placeBirth">Место рождения</param>
        public ForeignEntrepreneur(
            string taxpayerNumber,
            string regNumber,
            FullName fullName,
            EntrepreneurIdentityDocument document,
            DateTime dateBirth,
            string placeBirth)
        {
            TaxpayerNumber = taxpayerNumber;
            RegNumber = regNumber;
            Fullname = fullName;
            Document = document;
            DateBirth = dateBirth;
            PlaceBirth = placeBirth;
        }
        
        /// <summary>
        /// <para>Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</para>
        /// <para>Номер налогоплательщика присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомерНП")]
        public string TaxpayerNumber { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер в стране регистрации (инкорпорации) или его аналог, присвоенный иностранной организации</para>
        /// <para>Регистрационный номер присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер в стране регистрации (инкорпорации) или его аналог, присвоенный иностранной организации")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("РегНомер")]
        public string RegNumber { get; set; }
        
        /// <summary>
        /// <para>ФИО иностранного предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ФИО иностранного предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public SSP_API.Types.Xsd.FullName Fullname { get; set; }
        
        /// <summary>
        /// <para>Документ удостоверяющий личность индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Документ удостоверяющий личность индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ДокументЛичности")]
        public SSP_API.Types.Xsd.EntrepreneurIdentityDocument Document { get; set; }
        
        /// <summary>
        /// <para>Дата рождения индивидуального предпринимателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата рождения индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождения", DataType="date")]
        public System.DateTime DateBirth { get; set; }
        
        /// <summary>
        /// <para>Место рождения индивидуального предпринимателя</para>
        /// <para>Место рождения</para>
        /// <para xml:lang="en">Pattern: ([А-ЯЁ]+([ -][А-ЯЁ]+)*)|([A-Z]+([ -][A-Z]+)*).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Место рождения индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([А-ЯЁ]+([ -][А-ЯЁ]+)*)|([A-Z]+([ -][A-Z]+)*)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("МестоРождения")]
        public string PlaceBirth { get; set; }
    }
    
    /// <summary>
    /// <para>Запрос сведений о среднемесячных платежах</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Запрос сведений о среднемесячных платежах")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежах", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ЗапросСведенийОПлатежах", Namespace="")]
    public partial class SspRequest
    {
        /// <summary>
        /// Стандартный конструктор для сериализации
        /// </summary>
        public SspRequest() { }

        /// <summary>
        /// Инициализация <see cref="SspRequest"/>
        /// </summary>
        /// <param name="requestId">Уникальный идентификатор запроса в виде GUID</param>
        /// <param name="abonent">Сведения об абоненте (организации / лице, которое запрашивает сведения)</param>
        /// <param name="request">Содержание запроса ССП</param>
        /// <param name="requestType">Тип запроса</param>
        public SspRequest(
            string requestId,
            AbonentSspRequest abonent,
            RequestSspInfo request,
            RequestPaymentsInfoRequestType requestType = default)
        {
            RequestId = requestId;
            Abonent = abonent;
            Request = request;
            RequestType = requestType;
        }

        /// <summary>
        /// <para>Сведения об абоненте</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения об абоненте")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Абонент")]
        public AbonentSspRequest Abonent { get; set; } = new();

        /// <summary>
        /// <para>Содержание запроса сведений о среднемесячных платежах</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Содержание запроса сведений о среднемесячных платежах")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Запрос")]
        public RequestSspInfo Request { get; set; } = new();

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "1.2";

        /// <summary>
        /// <para>Версия схемы</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Версия схемы")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Версия")]
        public string Version 
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Уникальный идентификатор запроса присваивается абонентом, формирующим запрос</para>
        /// <para>Уникальный идентификатор</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Уникальный идентификатор запроса присваивается абонентом, формирующим запрос")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдентификаторЗапроса")]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>Тип запроса</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Тип запроса")]
        [System.ComponentModel.DescriptionAttribute("Тип запроса")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ТипЗапроса")]
        public RequestPaymentsInfoRequestType RequestType { get; set; }
    }

    /// <summary>
    /// <para>Сведения об абоненте</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахАбонент", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonentSspRequest
    {
        /// <summary>
        /// Конструктор для сериализации
        /// </summary>
        public AbonentSspRequest() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequest"/> ЮЛ
        /// </summary>
        /// <param name="legalEntity">Абонент - юридическое лицо</param>
        public AbonentSspRequest(AbonentSspRequestInfoLegalEntity legalEntity)
        {
            LegalEntity = legalEntity;
        }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequest"/> ИП
        /// </summary>
        /// <param name="individualEntrepreneur">Абонент - ИП</param>
        public AbonentSspRequest(AbonentSspRequestInfoIndividualEntrepreneur individualEntrepreneur)
        {
            IndividualEntrepreneur = individualEntrepreneur;
        }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequest"/> иностранного ЮЛ или ИП
        /// </summary>
        /// <param name="foreignPerson">Абонент - иностранное ЮЛ или ИП</param>
        public AbonentSspRequest(AbonentSspRequestInfoForeignPerson foreignPerson)
        {
            ForeignPerson = foreignPerson;
        }

        /// <summary>
        /// <para>Абонент - юридическое лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Абонент - юридическое лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ЮридическоеЛицо")]
        public AbonentSspRequestInfoLegalEntity LegalEntity { get; set; }
        
        /// <summary>
        /// <para>Абонент - индивидуальный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Абонент - индивидуальный предприниматель")]
        [System.Xml.Serialization.XmlElementAttribute("ИндивидуальныйПредприниматель")]
        public AbonentSspRequestInfoIndividualEntrepreneur IndividualEntrepreneur { get; set; }

        /// <summary>
        /// <para>Абонент - иностранное юридическое лицо или иностранный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Абонент - иностранное юридическое лицо или иностранный предприниматель")]
        [System.Xml.Serialization.XmlElementAttribute("ИностранноеЛицо")]
        public AbonentSspRequestInfoForeignPerson ForeignPerson { get; set; }
    }

    /// <summary>
    /// <para>Абонент - юридическое лицо</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахАбонентЮридическоеЛицо", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonentSspRequestInfoLegalEntity
    {
        /// <summary>
        /// Базовый конструктор для сериализации
        /// </summary>
        public AbonentSspRequestInfoLegalEntity() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequestInfoLegalEntity"/>
        /// </summary>
        /// <param name="inn">ИНН абонента</param>
        /// <param name="ogrn">ОГРН абонента</param>
        public AbonentSspRequestInfoLegalEntity(string inn, string ogrn)
        {
            Inn = inn;
            Ogrn = ogrn;
        }

        /// <summary>
        /// <para>ИНН юридического лица</para>
        /// <para>Индивидуальный номер налогоплательщика юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{10}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{10}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИНН")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН юридического лица</para>
        /// <para>Основной государственный регистрационный номер юридического лица</para>
        /// <para xml:lang="en">Pattern: \d{13}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН юридического лица")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{13}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРН")]
        public string Ogrn { get; set; }
    }

    /// <summary>
    /// <para>Абонент - индивидуальный предприниматель</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахАбонентИндивидуальныйПредприниматель", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonentSspRequestInfoIndividualEntrepreneur
    {
        /// <summary>
        /// Базовый конструктор для сериализации
        /// </summary>
        public AbonentSspRequestInfoIndividualEntrepreneur() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequestInfoIndividualEntrepreneur"/>
        /// </summary>
        /// <param name="inn">ИНН абонента</param>
        /// <param name="ogrn">ОГРН абонента</param>
        public AbonentSspRequestInfoIndividualEntrepreneur(string inn, string ogrn)
        {
            Inn = inn;
            Ogrn = ogrn;
        }

        /// <summary>
        /// <para>ИНН индивидуального предпринимателя</para>
        /// <para>Индивидуальный номер налогоплательщика физического лица</para>
        /// <para xml:lang="en">Pattern: \d{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИННИП")]
        public string Inn { get; set; }
        
        /// <summary>
        /// <para>ОГРН индивидуального предпринимателя</para>
        /// <para>Основной государственный регистрационный номер индивидуального предпринимателя</para>
        /// <para xml:lang="en">Pattern: \d{15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ОГРН индивидуального предпринимателя")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОГРНИП")]
        public string Ogrn { get; set; }
    }

    /// <summary>
    /// <para>Абонент - иностранное юридическое лицо или иностранный предприниматель</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахАбонентИностранноеЛицо", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonentSspRequestInfoForeignPerson
    {
        /// <summary>
        /// Базовый конструктор для сериализации
        /// </summary>
        public AbonentSspRequestInfoForeignPerson() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="AbonentSspRequestInfoForeignPerson"/>
        /// </summary>
        /// <param name="taxpayerNumber">Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</param>
        /// <param name="regNumber">Регистрационный номер в стране регистрации (инкорпорации) или его аналог</param>
        public AbonentSspRequestInfoForeignPerson(string taxpayerNumber, string regNumber)
        {
            TaxpayerNumber = taxpayerNumber;
            RegNumber = regNumber;
        }

        /// <summary>
        /// <para>Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</para>
        /// <para>Номер налогоплательщика присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомерНП")]
        public string TaxpayerNumber { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер в стране регистрации (инкорпорации) или его аналог</para>
        /// <para>Регистрационный номер присвоенный иностранным государством</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер в стране регистрации (инкорпорации) или его аналог")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("РегНомер")]
        public string RegNumber { get; set; }
    }

    /// <summary>
    /// <para>Содержание запроса сведений о среднемесячных платежах</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахЗапрос", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestSspInfo
    {
        /// <summary>
        /// Инициализация экземпляра <see cref="RequestSspInfo"/>
        /// </summary>
        /// <param name="source">Источник информации</param>
        /// <param name="subject"></param>
        /// <param name="consent"></param>
        /// <param name="amountObligations">Сумма обязательств</param>
        /// <param name="dateRequest">Дата запроса</param>
        public RequestSspInfo(
            SourceInfoRequest source,
            SubjectInfo subject,
            ConsentInfo consent,
            AmountObligations amountObligations)
        {
            Source = source;
            Subject = subject;
            Consent = consent;
            AmountObligations = amountObligations;
        }

        /// <summary>
        /// <para>Информация об организации или индивидуальном предпринимателе, запрашивающих сведения</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация об организации или индивидуальном предпринимателе, запрашивающих сведения")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Источник")]
        public SourceInfoRequest Source { get; set; } = new();

        /// <summary>
        /// <para>Сведения о субъекте кредитной истории</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Сведения о субъекте кредитной истории")]
        [System.ComponentModel.DescriptionAttribute("Сведения о субъекте кредитной истории")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Субъект")]
        public SSP_API.Types.Xsd.SubjectInfo Subject { get; set; } = new();

        /// <summary>
        /// <para>Сведения о согласии субъекта кредитной истории</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о согласии субъекта кредитной истории")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Согласие")]
        public ConsentInfo Consent { get; set; } = new();

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PurposeConsentInfo> _purpose;

        /// <summary>
        /// <para>Цель запроса</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Список целей запроса")]
        [System.ComponentModel.DescriptionAttribute("Цель запроса")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Цель")]
        public System.Collections.ObjectModel.Collection<PurposeConsentInfo> Purpose
        {
            get
            {
                return _purpose;
            }
            private set
            {
                _purpose = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestSspInfo" /> class.</para>
        /// </summary>
        public RequestSspInfo()
        {
            this._purpose = new System.Collections.ObjectModel.Collection<PurposeConsentInfo>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("СуммаОбязательства")]
        public AmountObligations AmountObligations { get; set; } = new();

        /// <summary>
        /// <para>Дата запроса</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата запроса")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Дата", DataType = "date")]
        public System.DateTime DateRequest { get; set; } = System.DateTime.UtcNow;
    }

    /// <summary>
    /// <para>Информация об организации или индивидуальном предпринимателе, запрашивающих сведения</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахЗапросИсточник", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SourceInfoRequest
    {
        /// <summary>
        /// Базовый конструктор для сериализации
        /// </summary>
        public SourceInfoRequest() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="SourceInfoRequest"/>
        /// </summary>
        /// <param name="source">Источник запроса <see cref="Xsd.LegalEntitySource"/></param>
        public SourceInfoRequest(LegalEntitySource source)
        {
            LegalEntitySource = source;
        }

        /// <summary>
        /// Инициализация экземпляра <see cref="SourceInfoRequest"/>
        /// </summary>
        /// <param name="source">Источник запроса <see cref="IndividualEntrepreneur"/></param>
        public SourceInfoRequest(IndividualEntrepreneur source)
        {
            IndividualEntrepreneurSource = source;
        }

        /// <summary>
        /// Инициализация экземпляра <see cref="SourceInfoRequest"/>
        /// </summary>
        /// <param name="source">Источник запроса <see cref="Xsd.ForeignLegalEntitySource"/></param>
        public SourceInfoRequest(ForeignLegalEntitySource source)
        {
            ForeignLegalEntitySource = source;
        }

        /// <summary>
        /// Инициализация экземпляра <see cref="SourceInfoRequest"/>
        /// </summary>
        /// <param name="source">Источник запроса <see cref="ForeignEntrepreneur"/></param>
        public SourceInfoRequest(ForeignEntrepreneur source)
        {
            ForeignEntrepreneurSource = source;
        }

        /// <summary>
        /// <para>Источник запроса - юридическое лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Источник запроса - юридическое лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ЮридическоеЛицо")]
        public LegalEntitySource LegalEntitySource { get; set; }
        
        /// <summary>
        /// <para>Источник запроса - индивидуальный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Источник запроса - индивидуальный предприниматель")]
        [System.Xml.Serialization.XmlElementAttribute("ИндивидуальныйПредприниматель")]
        public IndividualEntrepreneur IndividualEntrepreneurSource { get; set; }
        
        /// <summary>
        /// <para>Источник запроса - иностранное юридическое лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Источник запроса - иностранное юридическое лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ИностранноеЮЛ")]
        public ForeignLegalEntitySource ForeignLegalEntitySource { get; set; }
        
        /// <summary>
        /// <para>Источник запроса - иностранный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Источник запроса - иностранный предприниматель")]
        [System.Xml.Serialization.XmlElementAttribute("ИностранныйПредприниматель")]
        public ForeignEntrepreneur ForeignEntrepreneurSource { get; set; }
    }

    /// <summary>
    /// <para>Источник запроса - юридическое лицо</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахЗапросИсточникЮридическоеЛицо", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegalEntitySource : LegalEntity
    {
        private LegalEntitySource() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="LegalEntitySource"/>
        /// </summary>
        /// <param name="inn">ИНН</param>
        /// <param name="ogrn">ОГРН</param>
        /// <param name="fullName">Полное наименование</param>
        /// <param name="abbreviatedName">Сокращенное наименование</param>
        /// <param name="otherName">Иное наименование</param>
        /// <param name="userType">Код вида пользователя кредитной истории</param>
        public LegalEntitySource(
            string inn, 
            string ogrn,
            string fullName,
            string abbreviatedName,
            CreditHistoryUserType userType,
            string otherName = default)
        {
            Inn = inn; 
            Ogrn = ogrn;
            FullName = fullName;
            AbbreviatedName = abbreviatedName;
            OtherName = otherName;
            UserType = userType;
        }
    }

    /// <summary>
    /// <para>Источник запроса - иностранное юридическое лицо</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахЗапросИсточникИностранноеЮл", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignLegalEntitySource : ForeignLegalEntity
    {
        private ForeignLegalEntitySource() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="ForeignLegalEntitySource"/>
        /// </summary>
        /// <param name="taxpayerNumber">Номер налогоплательщика, присвоенный уполномоченным органом иностранного государства, или его аналог</param>
        /// <param name="regNumber">Регистрационный номер в стране регистрации (инкорпорации) или его аналог</param>
        /// <param name="lei">Идентификатор LEI</param>
        /// <param name="fullName">Полное наименование</param>
        /// <param name="abbreviatedName">Сокращенное наименование</param>
        /// <param name="userType">Код вида пользователя кредитной истории</param>
        /// <param name="otherName">Иное наименование</param>
        public ForeignLegalEntitySource(
            string taxpayerNumber,
            string regNumber,
            string lei,
            string fullName,
            string abbreviatedName,
            CreditHistoryUserType userType,
            string otherName = default)
        {
            TaxpayerNumber = taxpayerNumber;
            RegNumber = regNumber;
            Lei = lei;
            FullName = fullName;
            AbbreviatedName = abbreviatedName;
            OtherName = otherName;
            UserType = userType;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахЗапросСуммаОбязательства", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmountObligations
    {
        /// <summary>
        /// Базовый конструтктор для сериализации
        /// </summary>
        public AmountObligations() { }

        /// <summary>
        /// Инициализация экземпляра <see cref="AmountObligations"/>
        /// </summary>
        /// <param name="value">Сумма обязательств</param>
        /// <param name="currency">Валюта обязательства</param>
        public AmountObligations(double value, CurrencyType currency)
        {
            Value = value;
            Currency = currency;
        }

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Сумма обязательств")]
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value { get; set; }

        /// <summary>
        /// <para>Валюта обязательства</para>
        /// <para>Буквенный код валюты по ОКВ</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Валюта")]
        [System.ComponentModel.DescriptionAttribute("Валюта обязательства")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Валюта")]
        public CurrencyType Currency { get; set; }
    }

    /// <summary>
    /// <para>Тип запроса</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ЗапросСведенийОПлатежахТипЗапроса", Namespace="", AnonymousType=true)]
    public enum RequestPaymentsInfoRequestType
    {

        /// <summary>
        /// <para>Абонент запрашивает сведения одного квалифицированного бюро кредитных историй</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Сведения из одного бюро")]
        [System.ComponentModel.DescriptionAttribute("Абонент запрашивает сведения одного квалифицированного бюро кредитных историй")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        OneBureau,

        /// <summary>
        /// <para>Абонент запрашивает сведения из всех квалифицированных бюро кредитных историй путем обращения в одно из них ("Одно окно")</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = "Сведения из всех бюро")]
        [System.ComponentModel.DescriptionAttribute("Абонент запрашивает сведения из всех квалифицированных бюро кредитных историй путем обращения в одно из них (\"Одно окно\")")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        AllBureau,
    }
}
